[auth]
gcabrera = "wavetransition"
dazzarone = "wavetransition"
lbertran= "wavetransition"
showell= "wavetransition"
areaispinto= "wavetransition"
eschonberg= "wavetransition"
vtito= "wavetransition"
mmarnoni= "wavetransition"
cgully= "wavetransition"
mbenavides= "wavetransition"
lmaggioni= "wavetransition"


[profile.gcabrera]
first_name = "Gonzalo"

[profile.dazzarone]
first_name = "Donato"

[profile.lbertran]
first_name = "Luis"

[profile.showell]
first_name = "Sarah"

[profile.areaispinto]
first_name = "Adriana"

[profile.eschonberg]
first_name = "Enrique"

[profile.vtito]
first_name = "Verónica"

[profile.mmarnoni]
first_name = "Matteo"

[profile.cgully]
first_name = "Crystal"

[profile.mbenavides]
first_name = "Miguel"

[profile.lmaggioni]
first_name = "Lorenzo"




